# Generated by Django 2.2.13 on 2023-10-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_url', models.ImageField(blank=True, null=True, upload_to='templates/%Y%m%d')),
            ],
        ),
    ]
