# Generated by Django 2.2.13 on 2023-10-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_usergeneratedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('image_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Img',
            new_name='Imgg',
        ),
    ]
